# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_display', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
